[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA"

[build]
target = "thumbv7em-none-eabihf" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "trace"
EMBASSY_USB_MAX_HANDLER_COUNT = "6"
