[package]
name = "keyboard-link"
version = "0.1.0"
edition = "2021"

[dependencies]
async-hid = "0.4.4"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "sync", "macros", "time", "io-util"] }
futures = "0.3.31"
log = "0.4"
env_logger = "0.11.8"
